# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_cache_update
      when: ansible_os_family == "Debian"

    - name: Set users_to_add
      ansible.builtin.set_fact:
        users_list:
          - username: deploy

          - username: devops
            groups:
              - sudo

  roles:
    - { role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}" }
