# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        users_list:
          - username: deploy
          - username: devops
            groups:
              - sudo
