# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        users_list:
          - username: deploy
            ssh_keys:
              - ssh-ed25519 AAAAC3NzaC1 user1@email.com
              - ssh-ed25519 AAAAC3NzaC2 user2@email.com
              - ssh-ed25519 AAAAC3NzaC3 user3@email.com
          - username: devops
            groups:
              - sudo
            ssh_keys:
              - ssh-ed25519 AAAAC3NzaC1 user1@email.com
